# Generated by Django 3.1.4 on 2022-10-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddNewNote',
            new_name='Note',
        ),
    ]
